name: Check Stale Issues

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  check-stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check for stale issues
      uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale due to inactivity.'
        days-before-stale: 7
        days-before-close: 7
        stale-issue-label: 'Stale'
        only-labels: 'Needs Author Information'