name: Weekly Analytics Report

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: write
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install PyGithub python-dotenv
    
    - name: Generate Analytics Report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scripts/analytics_dashboard.py
    
    - name: Commit Report
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add weekly_triage_report.md triage_metrics_history.json
        git commit -m "Weekly triage analytics report" || echo "No changes to commit"
        git push